POST https://rq0q3cq4.directus.app/items/Clue HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlNjY5N2FiLTljMTAtNDc0OS04ZTIzLTk3ZWZjNzJjMzkxZiIsInJvbGUiOiI0MDhjZmZlMy00OWQyLTRkNDEtOTZkOS0xMjg2ZjAwOGViNGIiLCJhcHBfYWNjZXNzIjp0cnVlLCJhZG1pbl9hY2Nlc3MiOnRydWUsImlhdCI6MTY3ODI5NDkyOSwiZXhwIjoxNjc4Mjk1ODI5LCJpc3MiOiJkaXJlY3R1cyJ9.FSXlNhFxDHk3dVRJP36DrYDo477eE0_aWva9XR3TspI

{
    "name": "Yo",
    "riddle_id": 1
}