GET https://rq0q3cq4.directus.app/items/Games?fields=*,player.first_name&sort=-score&limit=10&filter[theme]=1 HTTP/1.1



# GET https://rq0q3cq4.directus.app/items/Games?fields=*&filter[theme]=1 HTTP/1.1