GET https://rq0q3cq4.directus.app/users?fields=first_name,email&filter[email]=vicky.georgiou2012@gmail.com HTTP/1.1

#  const getUsername = async () => {
#       const response = await fetch(import.meta.env.VITE_URL_DIRECTUS + "users?fields=first_name");
#       const json = await response.json();
#       users = json.data;
#       // console.log (users[0].first_name);
#       return users;
#     }